import { Workspace } from "@/components/workspace";
import { ArrowRight, Check, LayoutDashboard, LockKeyhole, Sparkles, Timer, Users } from "lucide-react";

const plans = [
  { name: "Starter", price: "$19", line: "For focused solo work", features: ["Unlimited projects", "50 tasks per project", "Basic priorities", "1 team member", "Task history"] },
  { name: "Pro", price: "$59", line: "For teams that ship weekly", popular: true, features: ["Unlimited projects", "Unlimited tasks", "Advanced filters", "10 team members", "API access", "30 day history"] },
  { name: "Enterprise", price: "$199", line: "For connected organizations", features: ["Everything in Pro", "50 team members", "Custom integrations", "Dedicated support", "Unlimited history"] },
];

export default function Home() {
  return <main className="overflow-hidden bg-white text-ink">
    <section id="product" className="bg-[radial-gradient(circle_at_75%_10%,#dceeff_0,transparent_32%),linear-gradient(#fff,#f8fbff)] px-4 pb-20 pt-28 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-7xl text-center">
        <div className="mx-auto mb-5 inline-flex items-center gap-2 rounded-full border border-blue/20 bg-white px-3 py-1.5 text-xs font-semibold text-blue shadow-sm"><Sparkles size={14}/> One workspace. Every project in motion.</div>
        <h1 className="mx-auto max-w-4xl text-balance text-4xl font-bold tracking-[-0.045em] text-ink sm:text-6xl lg:text-7xl">Move work forward without the busywork.</h1>
        <p className="mx-auto mt-6 max-w-2xl text-pretty text-base leading-7 text-slate sm:text-lg">Plan projects, assign priorities, and keep everyone synchronized in a workspace that stays fast as your team grows.</p>
        <div className="mt-8 flex flex-wrap justify-center gap-3"><a href="#workspace" className="inline-flex items-center gap-2 rounded-md bg-blue px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-blue/20 transition hover:bg-blue-dark">Try the live workspace <ArrowRight size={16}/></a><a href="#features" className="rounded-md border border-line bg-white px-5 py-3 text-sm font-semibold transition hover:border-blue/40 hover:text-blue">Explore features</a></div>
      </div>
      <div id="workspace" className="mx-auto mt-14 max-w-[1440px]"><Workspace /></div>
    </section>
    <section aria-label="Flowboard results" className="border-y border-line bg-white px-6 py-8"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-8 text-center lg:grid-cols-5">{[["247","active projects"],["3,841","tasks completed"],["12","team members"],["92%","completion rate"],["4.2 days","average to done"]].map(([n,l])=><div key={l}><div className="text-2xl font-bold tracking-tight text-ink">{n}</div><div className="mt-1 text-xs text-slate">{l}</div></div>)}</div></section>
    <section id="features" className="bg-soft px-6 py-24"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="eyebrow">Built for momentum</p><h2 className="section-title">Structure when you need it. Speed when you do not.</h2><p className="section-copy">Flowboard gives each project a clear home, then stays out of the way while your team gets to work.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-6">
      <article className="bento md:col-span-2 lg:col-span-4 lg:row-span-2"><div className="icon-box"><LayoutDashboard/></div><h3>One clear view of every commitment</h3><p>See projects, owners, priorities, and progress in a board that makes the next move obvious.</p><div className="mt-8 grid grid-cols-3 gap-2 rounded-lg border border-line bg-soft p-3">{["To Do","In Progress","Done"].map((x,i)=><div key={x} className="rounded-md bg-white p-3 text-xs font-semibold shadow-sm"><div className={`mb-8 h-1 rounded-full ${i===2?'bg-green':'bg-blue'}`}/>{x}</div>)}</div></article>
      <article className="bento md:col-span-1 lg:col-span-2"><div className="icon-box"><LockKeyhole/></div><h3>Changes that stay saved</h3><p>Projects and tasks persist securely through every refresh and handoff.</p></article><article className="bento md:col-span-1 lg:col-span-2"><div className="icon-box"><Users/></div><h3>Lightweight collaboration</h3><p>Assign teammates and understand ownership at a glance.</p></article><article className="bento md:col-span-1 lg:col-span-3"><div className="icon-box"><Timer/></div><h3>Metrics without manual reporting</h3><p>Track completion rate and time to done as the work changes.</p></article><article className="bento md:col-span-1 lg:col-span-3 bg-ink text-white"><div className="mb-8 flex items-center gap-2 text-xs text-white/60"><span className="h-2 w-2 rounded-full bg-green"/> Synced now</div><h3 className="text-white">A focused system your whole team can trust.</h3><p className="text-white/60">Clear status messaging, keyboard focus, and responsive views keep work accessible everywhere.</p></article>
    </div></div></section>
    <section id="pricing" className="px-6 py-24"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="eyebrow">Simple pricing</p><h2 className="section-title">Start focused. Scale together.</h2><p className="section-copy mx-auto">Every plan includes the essentials for moving projects from idea to done.</p></div><div className="mt-12 grid overflow-hidden rounded-xl border border-line lg:grid-cols-3">{plans.map((p)=><article key={p.name} className={`relative p-8 ${p.popular?'bg-blue text-white lg:-my-px lg:rounded-xl':'bg-white'} [&+article]:border-t lg:[&+article]:border-l lg:[&+article]:border-t-0`}>
      {p.popular&&<span className="absolute right-6 top-6 rounded-full bg-white px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-blue">Popular</span>}<h3 className="text-lg font-bold">{p.name}</h3><p className={`mt-2 text-sm ${p.popular?'text-white/70':'text-slate'}`}>{p.line}</p><div className="mt-8"><span className="text-4xl font-bold">{p.price}</span><span className={p.popular?'text-white/60':'text-slate'}>/month</span></div><a href="#workspace" className={`mt-7 block rounded-md px-4 py-2.5 text-center text-sm font-semibold ${p.popular?'bg-white text-blue':'bg-ink text-white'}`}>Start with {p.name}</a><ul className="mt-8 space-y-3">{p.features.map(f=><li key={f} className="flex gap-2 text-sm"><Check size={16} className={p.popular?'text-white':'text-green'}/>{f}</li>)}</ul></article>)}</div></div></section>
    <section id="customers" className="bg-soft px-6 py-24"><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Customer stories</p><h2 className="section-title">Less tool switching. More shipping.</h2></div><p className="max-w-sm text-sm leading-6 text-slate">Trusted by product teams, independent creators, and technical leaders who value clarity.</p></div><div className="mt-12 flex snap-x gap-5 overflow-x-auto pb-4">{[["SC","This tool replaced five different apps we were paying for. Our team now ships projects 40% faster.","Sarah Chen","Product Manager at TechVenture"],["MR","The simplicity is genius. Zero learning curve, and my freelance clients love the transparency.","Marcus Rodriguez","Freelance Creative Director"],["AW","We use this for sprint planning and it has become our single source of truth for task tracking.","Dr. Amelia Wu","Engineering Lead at DataCore Labs"]].map(([initials,quote,name,role])=><figure key={name} className="min-w-[88%] snap-center rounded-xl border border-line bg-white p-7 sm:min-w-[45%] lg:min-w-[32%]"><blockquote className="text-lg font-medium leading-8">“{quote}”</blockquote><figcaption className="mt-8 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-light text-xs font-bold text-blue">{initials}</span><span><strong className="block text-sm">{name}</strong><span className="text-xs text-slate">{role}</span></span></figcaption></figure>)}</div></div></section>
    <section id="faq" className="px-6 py-24"><div className="mx-auto grid max-w-5xl gap-12 lg:grid-cols-[.7fr_1fr]"><div><p className="eyebrow">Questions answered</p><h2 className="section-title">Everything you need to get moving.</h2><p className="section-copy">Flowboard is designed to be useful from the first project.</p></div><div className="divide-y divide-line border-y border-line">{[["Is my work saved between sessions?","Yes. Projects and tasks are stored server side, so changes remain available when you return."],["Can I move tasks between columns?","Yes. Drag any task between To Do, In Progress, and Done. The new status is saved immediately."],["Does Flowboard work on mobile?","Yes. The workspace adapts its navigation, board, and task details for smaller screens."],["Can I change plans later?","Yes. You can move between plans as your team and workflow change."]].map(([q,a])=><details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between font-semibold">{q}<span className="text-xl font-light text-blue group-open:rotate-45">+</span></summary><p className="max-w-xl pt-3 text-sm leading-6 text-slate">{a}</p></details>)}</div></div></section>
    <section className="px-6 pb-16"><div className="mx-auto max-w-6xl overflow-hidden rounded-2xl bg-blue px-6 py-16 text-center text-white shadow-2xl shadow-blue/20 sm:px-12"><h2 className="text-3xl font-bold tracking-tight sm:text-5xl">Your next project deserves a clearer path.</h2><p className="mx-auto mt-4 max-w-xl text-white/75">Open the live workspace, add your first task, and turn today’s priorities into visible progress.</p><a href="#workspace" className="mt-8 inline-flex items-center gap-2 rounded-md bg-white px-5 py-3 text-sm font-semibold text-blue">Start organizing <ArrowRight size={16}/></a></div></section>
  </main>;
}
