'use client'

import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, ChevronDown, Clock3, FolderKanban, LayoutGrid, LoaderCircle, Menu, MoreHorizontal, PanelLeftClose, Plus, Search, Trash2, X } from "lucide-react";

type Project = { id: number; name: string; description: string; created_at: string; task_count: number };
type Status = "todo" | "in-progress" | "done";
type Task = { id: number; project_id: number; title: string; description: string; priority: "low"|"medium"|"high"; status: Status; assignee: string; created_at: string; updated_at: string };

const columns: { id: Status; label: string; color: string }[] = [{id:"todo",label:"To Do",color:"bg-blue"},{id:"in-progress",label:"In Progress",color:"bg-amber-500"},{id:"done",label:"Done",color:"bg-green"}];

export function Workspace() {
  const [projects,setProjects]=useState<Project[]>([]), [tasks,setTasks]=useState<Task[]>([]);
  const [activeId,setActiveId]=useState<number|null>(null), [selected,setSelected]=useState<Task|null>(null);
  const [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [collapsed,setCollapsed]=useState(false);
  const [query,setQuery]=useState(""), [priority,setPriority]=useState("all"), [modal,setModal]=useState<"project"|"task"|null>(null), [taskStatus,setTaskStatus]=useState<Status>("todo");
  const active=projects.find(p=>p.id===activeId);
  const loadProjects=useCallback(async()=>{ const r=await fetch("/api/projects"); const data=await r.json(); setProjects(data); setActiveId(v=>v??data[0]?.id??null); },[]);
  const loadTasks=useCallback(async(id:number)=>{setLoading(true); const r=await fetch(`/api/tasks?projectId=${id}`); setTasks(await r.json()); setLoading(false)},[]);
  useEffect(()=>{loadProjects()},[loadProjects]); useEffect(()=>{if(activeId)loadTasks(activeId)},[activeId,loadTasks]);
  const filtered=useMemo(()=>tasks.filter(t=>t.title.toLowerCase().includes(query.toLowerCase())&&(priority==="all"||t.priority===priority)),[tasks,query,priority]);
  async function moveTask(id:number,status:Status){const old=tasks; setTasks(v=>v.map(t=>t.id===id?{...t,status}:t)); try{await fetch(`/api/tasks/${id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})})}catch{setTasks(old)}}
  async function updateTask(id:number, changes:Partial<Task>){setSaving(true);const r=await fetch(`/api/tasks/${id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(changes)});const updated=await r.json();setTasks(v=>v.map(t=>t.id===id?updated:t));setSelected(updated);setSaving(false)}
  async function createProject(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget);const r=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});const p=await r.json();setProjects(v=>[...v,p]);setActiveId(Number(p.id));setModal(null);setSaving(false)}
  async function createTask(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget);const r=await fetch("/api/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...Object.fromEntries(f),projectId:activeId,status:taskStatus})});const t=await r.json();setTasks(v=>[t,...v]);setProjects(v=>v.map(p=>p.id===activeId?{...p,task_count:Number(p.task_count)+1}:p));setModal(null);setSaving(false)}
  async function deleteTask(id:number){setSaving(true);await fetch(`/api/tasks/${id}`,{method:"DELETE"});setTasks(v=>v.filter(t=>t.id!==id));setProjects(v=>v.map(p=>p.id===activeId?{...p,task_count:Math.max(0,Number(p.task_count)-1)}:p));setSelected(null);setSaving(false)}
  return <div className="relative overflow-hidden rounded-xl border border-line bg-white text-left shadow-[0_25px_70px_rgba(31,41,55,.14)]">
    <div className="flex h-12 items-center justify-between border-b border-line px-4"><div className="flex items-center gap-2 text-sm font-bold"><span className="grid h-6 w-6 place-items-center rounded-md bg-blue text-white"><LayoutGrid size={14}/></span> Flowboard</div><div className="flex items-center gap-2"><span className="hidden items-center gap-2 text-xs text-slate sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-green"/>All changes saved</span><div className="grid h-7 w-7 place-items-center rounded-full bg-blue-light text-[10px] font-bold text-blue">ME</div></div></div>
    <div className="flex min-h-[610px]">
      <aside className={`${collapsed?'w-14':'w-52'} hidden shrink-0 flex-col border-r border-line bg-soft transition-all md:flex`}><div className="flex items-center justify-between px-3 py-4"><span className={`${collapsed?'hidden':''} text-[10px] font-bold uppercase tracking-widest text-slate`}>Projects</span><button onClick={()=>setCollapsed(v=>!v)} aria-label="Toggle project sidebar" className="rounded p-1.5 text-slate hover:bg-white"><PanelLeftClose size={15}/></button></div><div className="space-y-1 px-2">{projects.map(p=><button key={p.id} onClick={()=>setActiveId(Number(p.id))} className={`flex w-full items-center gap-2 rounded-md px-2 py-2 text-left text-xs font-medium transition ${activeId===Number(p.id)?'bg-white text-blue shadow-sm':'text-slate hover:bg-white/70'}`}><FolderKanban size={14} className="shrink-0"/><span className={`${collapsed?'hidden':'truncate flex-1'}`}>{p.name}</span><span className={`${collapsed?'hidden':''} rounded bg-gray-200 px-1.5 py-0.5 text-[9px] text-slate`}>{p.task_count}</span></button>)}</div><button onClick={()=>setModal("project")} className="m-3 mt-auto flex items-center justify-center gap-1.5 rounded-md bg-blue px-3 py-2 text-xs font-semibold text-white hover:bg-blue-dark"><Plus size={14}/><span className={collapsed?'hidden':''}>New Project</span></button></aside>
      <div className="min-w-0 flex-1"><header className="border-b border-line px-4 py-5 sm:px-6"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Menu size={18} className="md:hidden"/><h2 className="text-xl font-bold tracking-tight">{active?.name??"Loading workspace"}</h2><span className="rounded-full bg-green/10 px-2 py-1 text-[9px] font-bold uppercase tracking-wider text-green">Active</span></div><select aria-label="Choose project" value={activeId??""} onChange={e=>setActiveId(Number(e.target.value))} className="mt-2 max-w-52 rounded border border-line bg-white px-2 py-1 text-xs md:hidden">{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><p className="mt-1 max-w-xl text-xs text-slate">{active?.description}</p><p className="mt-2 flex items-center gap-1 text-[10px] text-slate"><CalendarDays size={11}/> Created {active?new Date(active.created_at).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):"recently"}</p></div><button onClick={()=>{setTaskStatus("todo");setModal("task")}} className="flex shrink-0 items-center gap-1 rounded-md bg-blue px-3 py-2 text-xs font-semibold text-white"><Plus size={14}/> <span className="hidden sm:inline">Add Task</span></button></div><div className="mt-5 flex flex-wrap gap-2"><label className="flex min-w-40 flex-1 items-center gap-2 rounded-md border border-line px-3 py-2"><Search size={14} className="text-slate"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks" className="w-full bg-transparent text-xs outline-none"/></label><label className="flex items-center gap-2 rounded-md border border-line px-3 text-xs text-slate">Priority <select value={priority} onChange={e=>setPriority(e.target.value)} className="bg-transparent font-semibold text-ink outline-none"><option value="all">All</option><option>high</option><option>medium</option><option>low</option></select><ChevronDown size={12}/></label></div></header>
      <div className="overflow-x-auto bg-[#fbfbfc] p-4 sm:p-6">{loading?<div className="grid h-80 place-items-center"><LoaderCircle className="animate-spin text-blue"/></div>:<div className="grid min-w-[760px] grid-cols-3 gap-4">{columns.map(c=><section key={c.id} onDragOver={e=>e.preventDefault()} onDrop={e=>moveTask(Number(e.dataTransfer.getData("task")),c.id)} className="min-h-[395px] rounded-lg border border-line bg-[#f7f8fa] p-3"><div className={`mb-3 h-0.5 rounded-full ${c.color}`}/><div className="mb-3 flex items-center justify-between"><h3 className="text-xs font-bold">{c.label} <span className="ml-1 text-slate">{filtered.filter(t=>t.status===c.id).length}</span></h3><MoreHorizontal size={14} className="text-slate"/></div><div className="space-y-2">{filtered.filter(t=>t.status===c.id).map(t=><button draggable onDragStart={e=>e.dataTransfer.setData("task",String(t.id))} onClick={()=>setSelected(t)} key={t.id} className="group block w-full cursor-grab rounded-md border border-line bg-white p-3 text-left shadow-[0_2px_8px_rgba(0,0,0,.05)] transition hover:border-blue/30 hover:shadow-md active:cursor-grabbing"><div className="flex items-start justify-between gap-2"><span className="text-xs font-semibold leading-5">{t.title}</span><MoreHorizontal size={13} className="shrink-0 text-slate opacity-0 group-hover:opacity-100"/></div><span className={`mt-3 inline-block rounded px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-wider priority-${t.priority}`}>{t.priority}</span><div className="mt-3 flex items-center justify-between text-[9px] text-slate"><span className="flex items-center gap-1"><Clock3 size={10}/>{new Date(t.updated_at).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</span><span className="grid h-6 w-6 place-items-center rounded-full bg-blue-light font-bold text-blue">{t.assignee}</span></div></button>)}</div><button onClick={()=>{setTaskStatus(c.id);setModal("task")}} className="mt-3 flex w-full items-center gap-1 rounded-md p-2 text-xs font-medium text-slate hover:bg-white hover:text-blue"><Plus size={13}/> Add Task</button></section>)}</div>}</div></div>
      {selected&&<aside className="absolute inset-y-12 right-0 z-20 w-full border-l border-line bg-white p-6 shadow-2xl sm:w-80"><button onClick={()=>setSelected(null)} aria-label="Close task details" className="absolute right-4 top-4 rounded p-1 hover:bg-soft"><X size={18}/></button><p className="text-[10px] font-bold uppercase tracking-wider text-blue">Task details</p><h3 className="mt-5 pr-8 text-xl font-bold">{selected.title}</h3><p className="mt-3 text-sm leading-6 text-slate">{selected.description||"No additional notes for this task."}</p><div className="mt-8 space-y-4 border-y border-line py-5 text-xs"><label className="flex items-center justify-between"><span className="text-slate">Status</span><select disabled={saving} value={selected.status} onChange={e=>updateTask(selected.id,{status:e.target.value as Status})} className="rounded border border-line bg-white px-2 py-1 font-semibold">{columns.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label className="flex items-center justify-between"><span className="text-slate">Priority</span><select disabled={saving} value={selected.priority} onChange={e=>updateTask(selected.id,{priority:e.target.value as Task["priority"]})} className="rounded border border-line bg-white px-2 py-1 font-semibold capitalize"><option>low</option><option>medium</option><option>high</option></select></label><div className="flex justify-between"><span className="text-slate">Assignee</span><strong>{selected.assignee}</strong></div></div><button disabled={saving} onClick={()=>deleteTask(selected.id)} className="mt-6 flex items-center gap-2 text-xs font-semibold text-red-600 disabled:opacity-50"><Trash2 size={14}/>Delete task</button></aside>}
    </div>
    {modal&&<div className="absolute inset-0 z-30 grid place-items-center bg-ink/30 p-4 backdrop-blur-[2px]"><form onSubmit={modal==="project"?createProject:createTask} className="w-full max-w-sm rounded-xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h3 className="text-lg font-bold">{modal==="project"?"Create a project":"Add a task"}</h3><button type="button" onClick={()=>setModal(null)} aria-label="Close form"><X size={18}/></button></div><div className="mt-5 space-y-3"><label className="block text-xs font-semibold">{modal==="project"?"Project name":"Task title"}<input required name={modal==="project"?"name":"title"} autoFocus className="mt-1.5 w-full rounded-md border border-line px-3 py-2.5 text-sm outline-none focus:border-blue focus:ring-2 focus:ring-blue/10"/></label><label className="block text-xs font-semibold">Description<textarea name="description" rows={3} className="mt-1.5 w-full resize-none rounded-md border border-line px-3 py-2.5 text-sm outline-none focus:border-blue"/></label>{modal==="task"&&<label className="block text-xs font-semibold">Priority<select name="priority" className="mt-1.5 w-full rounded-md border border-line bg-white px-3 py-2.5"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label>}</div><button disabled={saving} className="mt-5 flex w-full items-center justify-center gap-2 rounded-md bg-blue py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving?<LoaderCircle size={15} className="animate-spin"/>:<Check size={15}/>} {saving?"Saving…":modal==="project"?"Create project":"Add task"}</button></form></div>}
  </div>
}
